configure masqerade

diff --git a/script/configure b/script/configure
--- a/script/configure
+++ b/script/configure
@@ -6,15 +6,20 @@ function main {
 
   cd "$shome"
 
-  local nm_network="$(docker network inspect ubuntu_default | jq -r '.[].Name')"
+  local nm_network='ubuntu_default'
 
-  if [[ "$nm_network" != "ubuntu_default" ]]; then
+  local nm_network_found="$(docker network inspect "$nm_network" | jq -r '.[].Name')"
+
+  if [[ "$nm_network_found" != "$nm_network" ]]; then
     make up || true
   fi
+
+  sudo iptables -t nat -A POSTROUTING -s "$(docker network inspect "$nm_network" | jq -r '.[].IPAM.Config[].Subnet')" ! -o "$(facts | jq -r --arg gateway "$(docker network inspect "$nm_network" | jq -r '.[].IPAM.Config[].Gateway')"  'map(select(type == "object")) | map(select(.type == "bridge")) | map(select({gateway: .ipv4.address} == {gateway: $gateway})) | .[].device')" -j MASQUERADE
+  sudo sysctl -w net.ipv4.ip_forward=1
   
-  nm_network="$(docker network inspect ubuntu_default | jq -r '.[].Name')"
-  if [[ "$nm_network" != "ubuntu_default" ]]; then
-    echo "ERROR: could not bring up docker network for ubuntu" 1>&2
+  nm_network_found="$(docker network inspect "$nm_network" | jq -r '.[].Name')"
+  if [[ "$nm_network_found" != "$nm_network" ]]; then
+    echo "ERROR: could not bring up docker network $nm_network" 1>&2
     return 1
   fi
 
